from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AuditProfile:
    name: str
    description: str
    default_collectors: tuple[str, ...]
    delegated_role_hints: tuple[str, ...]
    app_escalation_permissions: tuple[str, ...]
    supported_planes: tuple[str, ...]
    supported_probe_modes: tuple[str, ...]
    adapter_requirements: tuple[str, ...]
    response_allowed: bool
    notes: str


PROFILES: dict[str, AuditProfile] = {
    "auto": AuditProfile(
        name="auto",
        description="Run the selected collectors and record gaps without assuming a fixed role.",
        default_collectors=(
            "identity",
            "app_consent",
            "security",
            "conditional_access",
            "defender",
            "service_health",
            "auth_methods",
            "reports_usage",
            "external_identity",
            "consent_policy",
            "domains_hybrid",
            "licensing",
            "intune",
            "sharepoint",
            "onedrive_posture",
            "teams",
        ),
        delegated_role_hints=("Global Reader",),
        app_escalation_permissions=(),
        supported_planes=("inventory", "full"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=(),
        response_allowed=False,
        notes="Use for unknown delegated tokens and let diagnostics describe missing visibility.",
    ),
    "global-reader": AuditProfile(
        name="global-reader",
        description="Read-only delegated audit path for Entra, M365, and basic workload posture.",
        default_collectors=(
            "identity",
            "app_consent",
            "security",
            "conditional_access",
            "defender",
            "service_health",
            "auth_methods",
            "reports_usage",
            "external_identity",
            "consent_policy",
            "domains_hybrid",
            "licensing",
            "intune",
            "sharepoint",
            "sharepoint_access",
            "onedrive_posture",
            "teams",
        ),
        delegated_role_hints=("Global Reader",),
        app_escalation_permissions=(
            "Policy.Read.All",
            "Directory.Read.All",
            "DelegatedPermissionGrant.Read.All",
            "Application.Read.All",
            "AuditLog.Read.All",
            "SecurityEvents.Read.All",
            "SecurityIncident.Read.All",
            "SecurityAlert.Read.All",
            "DeviceManagementManagedDevices.Read.All",
            "Organization.Read.All",
            "Reports.Read.All",
            "ReportSettings.Read.All",
            "Sites.Read.All",
            "ServiceHealth.Read.All",
            "ServiceMessage.Read.All",
        ),
        supported_planes=("inventory", "full", "export"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=(),
        response_allowed=False,
        notes="Preferred first-pass profile for customer-led browser login without app consent.",
    ),
    "security-reader": AuditProfile(
        name="security-reader",
        description="Focused delegated audit for security posture, risk, and alerts.",
        default_collectors=("identity", "app_consent", "security", "conditional_access", "defender", "auth_methods", "identity_governance"),
        delegated_role_hints=("Security Reader", "Global Reader"),
        app_escalation_permissions=(
            "SecurityEvents.Read.All",
            "AuditLog.Read.All",
            "Reports.Read.All",
            "Policy.Read.All",
            "DelegatedPermissionGrant.Read.All",
            "Application.Read.All",
            "AccessReview.Read.All",
            "EntitlementManagement.Read.All",
            "RoleManagement.Read.Directory",
            "ServiceHealth.Read.All",
            "ServiceMessage.Read.All",
        ),
        supported_planes=("inventory", "full", "export"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=(),
        response_allowed=False,
        notes="Use when the customer grants Security Reader but not broader workload access.",
    ),
    "reports-reader": AuditProfile(
        name="reports-reader",
        description="Focused delegated audit for Microsoft 365 usage and service health reporting surfaces.",
        default_collectors=("identity", "security", "service_health", "reports_usage"),
        delegated_role_hints=("Reports Reader", "Global Reader"),
        app_escalation_permissions=(
            "Reports.Read.All",
            "ReportSettings.Read.All",
            "ServiceHealth.Read.All",
            "ServiceMessage.Read.All",
            "AuditLog.Read.All",
        ),
        supported_planes=("inventory", "full"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=(),
        response_allowed=False,
        notes="Use when the customer grants a reporting-focused delegated role for usage and health evidence.",
    ),
    "exchange-reader": AuditProfile(
        name="exchange-reader",
        description="Focused delegated audit for Exchange Online configuration and mail flow evidence.",
        default_collectors=("exchange", "exchange_policy", "security", "identity"),
        delegated_role_hints=("Exchange Reader", "Global Reader"),
        app_escalation_permissions=("Exchange.ManageAsApp",),
        supported_planes=("inventory", "full", "export"),
        supported_probe_modes=("delegated", "app", "response"),
        adapter_requirements=("m365_cli", "powershell_graph"),
        response_allowed=True,
        notes="Uses command-based Exchange collection where Graph coverage is limited.",
    ),
    "intune-reader": AuditProfile(
        name="intune-reader",
        description="Focused delegated audit for Intune devices, compliance, and configuration.",
        default_collectors=("intune", "intune_depth"),
        delegated_role_hints=("Intune Reader", "Global Reader"),
        app_escalation_permissions=(
            "DeviceManagementConfiguration.Read.All",
            "DeviceManagementManagedDevices.Read.All",
            "DeviceManagementApps.Read.All",
        ),
        supported_planes=("inventory", "full"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=(),
        response_allowed=False,
        notes="Useful when Global Reader does not expose the device-management surfaces needed.",
    ),
    "app-readonly-full": AuditProfile(
        name="app-readonly-full",
        description="Customer-local app-only read path for deep unattended evidence collection.",
        default_collectors=(
            "identity",
            "app_consent",
            "security",
            "conditional_access",
            "defender",
            "service_health",
            "auth_methods",
            "reports_usage",
            "external_identity",
            "consent_policy",
            "domains_hybrid",
            "licensing",
            "identity_governance",
            "intune",
            "intune_depth",
            "sharepoint",
            "sharepoint_access",
            "onedrive_posture",
            "teams",
            "teams_policy",
            "purview",
            "ediscovery",
            "exchange",
            "exchange_policy",
        ),
        delegated_role_hints=(),
        app_escalation_permissions=(
            "Directory.Read.All",
            "DelegatedPermissionGrant.Read.All",
            "Application.Read.All",
            "Policy.Read.All",
            "AuditLog.Read.All",
            "SecurityEvents.Read.All",
            "SecurityIncident.Read.All",
            "SecurityAlert.Read.All",
            "DeviceManagementConfiguration.Read.All",
            "DeviceManagementManagedDevices.Read.All",
            "DeviceManagementApps.Read.All",
            "Organization.Read.All",
            "Reports.Read.All",
            "ReportSettings.Read.All",
            "Sites.Read.All",
            "ServiceHealth.Read.All",
            "ServiceMessage.Read.All",
            "AccessReview.Read.All",
            "EntitlementManagement.Read.All",
            "RoleManagement.Read.Directory",
            "eDiscovery.Read.All",
            "Exchange.ManageAsApp",
        ),
        supported_planes=("inventory", "full", "export"),
        supported_probe_modes=("delegated", "app"),
        adapter_requirements=("m365_cli", "powershell_graph"),
        response_allowed=False,
        notes="Secondary pass only. Use a customer-local app registration and keep permissions read-only.",
    ),
}


def profile_choices() -> list[str]:
    return list(PROFILES.keys())


def get_profile(name: str) -> AuditProfile:
    return PROFILES.get(name, PROFILES["auto"])
